# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Henri Tuomola"
description: > # this means to ignore newlines until "email:"
   Software developer and hobbyist photographer

email: henri@mnd.fi
#blog logo
logo: "/assets/images/logo_ht.png"
# blog cover
cover: "/assets/images/site_bg.jpg"

name: 'Henri Tuomola'
author: 'Henri Tuomola'
author_image: "/assets/images/author.jpg"

permalink: /blog/:year/:month/:day/:title/

disqus_shortname: henrituomola

paginate:	5
paginate_path: "/blog/page:num"

url: "http://www.mnd.fi" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

gems:
  - jekyll-redirect-from

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/htuomola
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/henri.tuomola
    desc: Connect with me facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/htuomola
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	flickr
    url:	https://www.flickr.com/htuomola
    desc:	Connect with me on Flickr
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	http://fi.linkedin.com/in/henrituomola
    desc:	Connect with me on LinkedIn
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
