# Build settings
markdown: redcarpet
highlighter: rouge

# Site settings
title: "Henri Tuomola"
description: > # this means to ignore newlines until "email:"
   Software developer and hobbyist photographer

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Henri Tuomola'
author: 'Henri Tuomola'
author_image: "/assets/images/author.jpg"

permalink: /blog/:categories/:year/:month/:day/:title/

paginate:	5
paginate_path: "/blog/page:num"

url: "http://www.henrituomola.fi" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/htuomola
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/henri.tuomola
    desc: Connect with me facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/htuomola
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
